# Installs required R libraries
install.packages('yaml', repos='https://cloud.r-project.org/')
install.packages('ggpubr', repos = 'https://cloud.r-project.org/', dependencies = TRUE)
install.packages('tidyverse', repos='https://cloud.r-project.org/')
install.packages('BiocManager', repos='https://cloud.r-project.org/')
BiocManager::install(c('BiocParallel', 'TCGAbiolinks', 'HDF5Array', 'affycoretools', 'affyPLM', 'hgu133plus2.db', 'qvalue', 'sva'))
install.packages('devtools', repos='https://cloud.r-project.org/')
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec()
devtools::install_github('zhangyuqing/sva-devel')
